<!Doctype html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8"/>
        <title>Sistema de controle de animais</title>
    </head>
    <body>
        <h2 text align="center">Sistema de Contole de Animais - PET SHOP</h2>
        <fieldset text align="center">
            <a href="cadastro_animais.php">Cadastro de Animais</a> |
            <a href="lista_animais.php">Listagem dos Animais</a> |
            <a href="pesquisa_nome.php">Pesquisar animal por nome</a> |
        </fieldset>
    </body>
</html>